name: ministore
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter

  installed_apps: ^1.2.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.6
  device_apps: ^2.1.1
  flutter_appavailability: ^0.0.21
  flutter_local_notifications: ^6.0.0
  workmanager: ^0.4.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
